import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const ciTest = process.argv[2] === 'ci-test';
const dev = process.argv[2] === 'development';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules,
    ],
    loader: {
        '.wasm': 'binary',
        '.lua': 'text',
    },
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
    define: {
        __DEV__: prod ? 'false' : 'true',
    },
});

if (prod || ciTest) {
    await context.rebuild();
    process.exit(0);
} else if (dev) {
    await context.rebuild();
    // copy the generated file to the plugin folder
    fs.mkdirSync('./test-vault/.obsidian/plugins/vim-motions-tparsons9', {
        recursive: true,
    });
    fs.copyFileSync(
        'main.js',
        './test-vault/.obsidian/plugins/vim-motions-tparsons9/main.js',
    );
    fs.copyFileSync(
        'manifest.json',
        './test-vault/.obsidian/plugins/vim-motions-tparsons9/manifest.json',
    );
    fs.copyFileSync(
        'styles.css',
        './test-vault/.obsidian/plugins/vim-motions-tparsons9/styles.css',
    );
    process.exit(0);
} else {
    await context.watch();
}
